---
title: TIGERLIHAO
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:year/:month/:day/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
markdown: kramdown
pygments: true
tagline: Li Hao's Site
author:
  name: tigerlihao
  email: blah@email.test
  github: tigerlihao
  twitter: tigerlihao
  feedburner: feedname
production_url: http://tigerlihao.com
google_analytics_id: UA-10752284-7
duoshuo_short_name: tigerlihao
archive_path: "/archive/"
categories_path: "/categories/"
tags_path: "/tags/"
cat_names:
  journal: 日志
  study: 学习
